apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainguard-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: chainguard-demo-app
          image: bannimal/chainguard-test-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: chainguard-demo-app
spec:
 type: LoadBalancer
 selector:
   app: java-app
 ports:
   - protocol: TCP
     port: 80
     targetPort: 8080